# This is a test script to generate a SIMION PA with python
# Date: 2018/05/22
# Author: izpilab, gaudee, ehu
# Description:
#   We will generate a set of PAs file for the repller of our
#   ion source. It is composed by:
#       PE: Plasma electrode. with width WIDTHS[0] 
#       D# (D4, D6, Dn): A set of three discs that have a central
#                   hole with the diamter given by the number # in D#.
#                   Their widths will be given in WIDTHS
#       The distances between electrodes is given in DISTS.
#
# The pa# will be saved into "current_folder\pas\filename\filename.pa#"
#
# Usage:
#   1.- Set the range of the parameter to change.
#       WARNING: Be careful because the minimum resolution is 0.25mm
#   2.- Set DISTS with the distances between first
#       second and third electrodes. The plasma electrode will be
#       generated by default.
#       Just change the distance to iterate with a param.
#   2.- Set which electrode, D#, is required in each position at
#       the ELECS list. # will be the diamter of the central hole.
#       Just change the diameter to iterate with
#       'D'+'{0:g}'.format(param).
#   3.- Set WIDTHS list with the widths of the electrodes. First PE
#       and then the first, second and third elecrode.
#       Just change the distance to iterate with a param.


#------------------------------ IMPORTS ----------------------------------#

from libs.ElectrodeGenLib.gen_electrode_set_width import *
import numpy as np
import sys

if __name__ == "__main__":
    # print(len(sys.argv))
    if len(sys.argv) > 2:
        x_width = sys.argv[1]
        x_width = float(x_width)
        y_height = sys.argv[2]
        y_height = float(y_height)
    elif len(sys.argv) > 1:
        x_width = sys.argv[1]
        x_width = float(x_width)
        y_height = 0  # For backward compatibility.
    else:
        x_width = 0  # For backward compatibility.
        y_height = 0  # For backward compatibility.

    #------------------------------ DEFINES ----------------------------------#
    for param in np.arange (8.0,8.25,0.25): # Generates only 1
        WIDTHS = [4, 4, 8, 4]        # Widths of the electrodes (mm)
        # Distance between PE and 1st Electrode (mm)
        # Distance between 1st and 2nd Electrode (mm)
        # Distance between 2ndand 3rd Electrode (mm)
        DISTS = [32, 7, 6]
        ELECS = ['D11', 'D12', 'D10']  # Electrodes arrangement
        # ELECS = ['D1', 'D'+'{0:g}'.format(param), 'D5']  # Electrodes arrangement
        


        #------------------------------ PROGRAM ----------------------------------#

        # Generate the filename from geomtry
        FILENAME = gen_pa_name_from_data(WIDTHS[0], DISTS[0],
                            ELECS[0], WIDTHS[1], DISTS[1],
                            ELECS[1], WIDTHS[2], DISTS[2],
                            ELECS[2], WIDTHS[3])

        # Generate a pa# file with the requiered structure
        # It is saved into "current_folder\pas\filename\filename.pa#"
        gen_electrodes_set_pa(x_width, y_height, DISTS, ELECS, WIDTHS, FILENAME)
